#!/usr/bin/env python3
import argparse
import sys
import time
from collections import deque

try:
    import matplotlib.pyplot as plt
    import matplotlib.patches as patches
except ImportError:
    print("Missing dependency: matplotlib. Install with: pip install matplotlib", file=sys.stderr)
    raise

try:
    import serial
except ImportError:
    print("Missing dependency: pyserial. Install with: pip install pyserial", file=sys.stderr)
    raise

from classify_h2_lut import average_samples, classify, load_lut, read_h2_frame


def unique_key_names(entries):
    keys = {}
    for entry in entries:
        keys[entry["key_id"]] = entry["key_name"]
    return [keys[key_id] for key_id in sorted(keys)]


class KeyboardDisplay:
    def __init__(self, key_names):
        self.key_names = key_names
        self.rectangles = {}
        self.labels = {}

        plt.ion()
        self.figure, self.axis = plt.subplots(1, 1, figsize=(10, 3))
        self.axis.set_xlim(0, len(key_names))
        self.axis.set_ylim(0, 1)
        self.axis.set_aspect("equal", adjustable="box")
        self.axis.axis("off")
        self.status_text = self.axis.text(
            0.5,
            1.18,
            "Waiting for stable key...",
            transform=self.axis.transAxes,
            ha="center",
            va="center",
            fontsize=14,
        )

        for index, key_name in enumerate(key_names):
            rect = patches.Rectangle(
                (index + 0.05, 0.05),
                0.9,
                0.9,
                linewidth=2,
                edgecolor="black",
                facecolor="#dddddd",
            )
            self.axis.add_patch(rect)
            label = self.axis.text(
                index + 0.5,
                0.5,
                key_name,
                ha="center",
                va="center",
                fontsize=18,
                fontweight="bold",
            )
            self.rectangles[key_name] = rect
            self.labels[key_name] = label

        self.figure.tight_layout()
        self.figure.show()

    def update(self, current_key, stable_key, result):
        for key_name, rect in self.rectangles.items():
            if stable_key == key_name:
                rect.set_facecolor("#33cc66")
            elif current_key == key_name:
                rect.set_facecolor("#ffd966")
            else:
                rect.set_facecolor("#dddddd")

        if stable_key == "NO_SIGNAL":
            title = "NO SIGNAL"
        elif stable_key:
            title = f"Pressed: {stable_key}"
        else:
            title = f"Detecting: {current_key}"

        self.status_text.set_text(
            f"{title}    score={result['score']:.4g}    total={result['total_g2']:.4f} G^2"
        )
        self.figure.canvas.draw_idle()
        self.figure.canvas.flush_events()
        plt.pause(0.001)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Animate live magnetic-key classification from FPGA H2 UART data."
    )
    parser.add_argument("port", help="Serial port, e.g. COM5 or /dev/ttyUSB0.")
    parser.add_argument("--lut", required=True, help="CSV generated by collect_h2_lut.py.")
    parser.add_argument("--baud", "-baud", type=int, default=115200)
    parser.add_argument("--frequency", choices=["75", "45"], default="75")
    parser.add_argument("--average", type=int, default=10)
    parser.add_argument("--stable", type=int, default=3)
    parser.add_argument("--strength-weight", type=float, default=0.05)
    parser.add_argument("--min-total-g2", type=float, default=0.0)
    parser.add_argument(
        "--refresh-hz",
        type=float,
        default=30.0,
        help="Maximum Matplotlib refresh rate.",
    )
    args = parser.parse_args()

    entries = load_lut(args.lut, args.frequency)
    key_names = unique_key_names(entries)
    display = KeyboardDisplay(key_names)
    sample_window = deque(maxlen=max(1, args.average))
    key_history = deque(maxlen=max(1, args.stable))
    refresh_period = 1.0 / args.refresh_hz if args.refresh_hz > 0 else 0.0
    last_refresh = 0.0

    print(f"Loaded {len(entries)} LUT entries from {args.lut}")
    print(f"Animating {args.frequency} Hz classifications from {args.port}")
    print("Close the plot window or press Ctrl-C to stop.")

    try:
        with serial.Serial(args.port, args.baud, timeout=1) as ser:
            while plt.fignum_exists(display.figure.number):
                frame = read_h2_frame(ser)
                sample_window.append(frame[args.frequency])

                if len(sample_window) < sample_window.maxlen:
                    continue

                values = average_samples(sample_window)
                result = classify(values, entries, args.strength_weight)

                if result["total_g2"] < args.min_total_g2:
                    key_history.clear()
                    stable_key = "NO_SIGNAL"
                else:
                    key_history.append(result["key_name"])
                    if (
                        len(key_history) == key_history.maxlen
                        and all(key == result["key_name"] for key in key_history)
                    ):
                        stable_key = result["key_name"]
                    else:
                        stable_key = None

                now = time.time()
                if now - last_refresh >= refresh_period:
                    display.update(result["key_name"], stable_key, result)
                    last_refresh = now

    except KeyboardInterrupt:
        print("\nStopped.")
        return 0

    print("Plot window closed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
